version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: app_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: app_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/app_db
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  pgdata: