name: Terraform AWS Deployment

on:
  workflow_dispatch: # Manual trigger

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Debug: Check secrets availability
      - name: Debug Secrets
        run: |
          echo "AWS_REGION is set to: ${{ secrets.AWS_REGION }}"
          echo "AWS_ROLE_ARN is set to: ${{ secrets.AWS_ROLE_ARN }}"
          if [ -z "${{ secrets.AWS_REGION }}" ]; then
            echo "Error: AWS_REGION secret is not set or empty"
            exit 1
          fi
          if [ -z "${{ secrets.AWS_ROLE_ARN }}" ]; then
            echo "Error: AWS_ROLE_ARN secret is not set or empty"
            exit 1
          fi

      # Set up AWS CLI
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      # Generate Terraform Plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        working-directory: ./infra

      # Upload plan file as artifact
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ./terraform/tfplan
          retention-days: 1

      # Manual Approval
      - name: Wait for Approval
        uses: actions/attest@v1
        with:
          subject: "Terraform Plan Approval"
          predicate-type: "manual-approval"

      # Download plan file
      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ./infra

      # Apply Terraform Plan
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./infra