name: Terraform AWS Deployment

on:
  workflow_dispatch: # Manual trigger

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write
  repository-projects: write 

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Debug: Check secrets availability
      - name: Debug Secrets
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
        run: |
          echo "AWS_REGION is set to: $AWS_REGION"
          echo "AWS_ROLE_ARN is set to: $AWS_ROLE_ARN"
          if [ -z "$AWS_REGION" ]; then
            echo "Error: AWS_REGION secret is not set or empty"
            exit 1
          fi
          if [ -z "$AWS_ROLE_ARN" ]; then
            echo "Error: AWS_ROLE_ARN secret is not set or empty"
            exit 1
          fi

      # Set up AWS CLI
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      # Generate Terraform Plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        working-directory: ./infra

      # Upload plan file as artifact
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ./infra/tfplan
          retention-days: 1

      # Manual Approval
      - name: Wait for Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ github.repository_owner }} # Thay bằng username GitHub của người phê duyệt hoặc để yên để luôn gắn chủ của repo làm người 
          minimum-approvals: 1
          issue-title: "Approve Terraform Plan"
          issue-body: "Please review and approve the Terraform plan to proceed with deployment."
          fail-on-denial: true


      # Download plan file
      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ./infra

      # Apply Terraform Plan
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./infra